### PR TITLE
fix cqlsh

### PR DESCRIPTION
**Pull request by FRidh**
The script seems to run.
If this works for you, please merge and rebase.

### CODE REVIEW

**Comment by markus1189** [comment]
Before the change I was also able to run it.  Problem is that there is no TAB completion because python is missing the `readline` library when the script is started.  As an example you can try to do enter e.g. `SEL<tab>` which should trigger completion and not insert raw tabs...

**Comment by FRidh** [comment]
I don't have any server set up so I don't know how I could easily test this.

**Comment by FRidh** [comment]
I just added `readline`. The following seems to work:
`nix-shell -p cassandra -I nixpkgs=. --pure --run "python -c 'import sqlite3; import readline;'"`

and 

```
$ echo $PYTHONPATH
/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/site-packages:/nix/store/rc445bsxb245k2xb86y2w6qi1w6k8rpg-python-sqlite3-2.7.11/lib/python2.7/site-packages:/nix/store/6nbdrsd6myqgs7vym3kpzwfslswqqrlx-python-readline-2.7.11/lib/python2.7/site-packages
```

Because `$PYTHONPATH` includes both it should be working.

**Comment by markus1189** [comment]
That is strange because this is what I get when I run it from the cloned `nixpkgs` directory with your commit checked out:

```
clones/nixpkgs > git status                                                                                     
On branch pr1
nothing to commit, working directory clean
clones/nixpkgs > git show -s                                                                                    
commit 2da4ca84dfe96a1997558a1143301857460456cf
Author: Frederik Rietdijk <fridh@fridh.nl>
Date:   Thu Mar 31 09:45:00 2016 +0200

    fix cqlsh
clones/nixpkgs > nix-shell -p cassandra -I nixpkgs=. --pure --run "python -c 'import sqlite3; import readline;'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named readline
```

**Comment by markus1189** [comment]
Ah nevermind I didn't pull in your change for `readline`. But unfortunately it still does not work...

**Comment by markus1189** [comment]
I have added a temporary debug print statement to the python script in deb3d32737f7f75e4ba6e96a125e951e6b562006, it still fails to load `readline` somehow...
If I start it I see the `no readline` printed so seems like there is still some problem.

You should also see the output even if there is no cassandra running, maybe this helps you with debugging ;)

**Comment by FRidh** [comment]
I've updated the PR and readline imports just fine. 

```
$ nix-shell -p cassandra -I nixpkgs=. --pure --run "cqlsh"
<module 'readline' from '/nix/store/447rz3p9462jpyiar56fshzj9fq3gh62-python-readline-2.7.11/lib/python2.7/site-packages/readline.so'>
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```

Nothing wrong here with the Nix expression. 
Maybe something with `if sys.stdin.isatty():` in the script?

**Comment by markus1189** [comment]
I must be missing something then.  Checking out your commit:

```
clones/nixpkgs > git show -s                   
commit 8241689c82086c2fcaeff41eb6fc0e43213de2db
Author: Frederik Rietdijk <fridh@fridh.nl>
Date:   Thu Mar 31 22:26:58 2016 +0200

    demonstrate readline works
```

and running cqlsh I get:

```
clones/nixpkgs > result/bin/cqlsh                 
Traceback (most recent call last):
  File "result/bin/cqlsh.py", line 40, in <module>
    import readline; print(readline)
ImportError: No module named readline
```

it works with your example above for me too:

```
clones/nixpkgs > nix-shell -p cassandra -I nixpkgs=. --pure --run "cqlsh"                                                                                     
<module 'readline' from '/nix/store/447rz3p9462jpyiar56fshzj9fq3gh62-python-readline-2.7.11/lib/python2.7/site-packages/readline.so'>
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```

maybe there is still something missing to make it work outside a nix-shell?

**Comment by FRidh** [comment]
Possible cause: https://github.com/NixOS/nix/issues/886

Edit:
Okay, that is not related.

**Pull request closed without merging**
